# The URL the site will be built for
base_url = "https://thelion.website"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "The Lion"

generate_feed = true
feed_filename = "atom.xml"
feed_url = "/atom.xml"

insert_anchor_links = "right"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
# Put all your custom variables here
links = [ {url = "/about/", name = "About"},
]

identities_social = {"Mastodon" = "https://mastodon.thelion.website"}
identities_editing = {"OpenStreetMap" = "https://openstreetmap.thelion.website", "Wikipedia" = "https://wikipedia.thelion.website"}
identities_discussion = {"Tildes" = "https://tildes.thelion.website", "Reddit" = "https://reddit.thelion.website", "GNOME Discourse" = "https://discourse-gnome.thelion.website"}
identities_coding = {"GitHub" = "https://github.thelion.website", "Codeberg" = "https://codeberg.thelion.website", "GitLab.com" = "https://gitlab.thelion.website", "GNOME GitLab" = "https://gitlab-gnome.thelion.website", "FreeDesktop GitLab" = "https://gitlab-freedesktop.thelion.website"}
identities_tracking = {"Anidb" = "https://anidb.thelion.website", "Listenbrainz" = "https://listen.thelion.website"}
identities_chatting = {"Discord (using a tool a friend made, pretty neat)" = "https://discord.thelion.website", "Matrix" = "https://matrix.thelion.website"}
