# The URL the site will be built for
base_url = "https://thelion.website"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "The Lion"

generate_feed = true
feed_filename = "atom.xml"
feed_url = "/atom.xml"

insert_anchor_links = "right"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
# Put all your custom variables here
links = [ {url = "/atom.xml", name = "Feed"},
	  {url = "/projects/", name = "Projects"},
	  {url = "/anime/", name = "Anime"},
	  {url = "/about/", name = "About"},
]

identities_social = {"Mastodon" = "https://mastodon.thelion.website"}
identities_editing = {"OpenStreetMap" = "https://openstreetmap.thelion.website", "Wikipedia" = "https://wikipedia.thelion.website"}
identities_discussion = {"Tildes" = "https://tildes.thelion.website", "Reddit" = "https://reddit.thelion.website", "GNOME Discourse" = "https://discourse-gnome.thelion.website"}
identities_coding = {"GitHub" = "https://github.thelion.website", "Codeberg" = "https://codeberg.thelion.website", "GitLab.com" = "https://gitlab.thelion.website", "GNOME GitLab" = "https://gitlab-gnome.thelion.website", "FreeDesktop GitLab" = "https://gitlab-freedesktop.thelion.website"}
identities_tracking = {"Anidb" = "https://anidb.thelion.website", "Listenbrainz" = "https://listen.thelion.website"}
identities_chatting = {"Discord (using a tool a friend made, pretty neat)" = "https://discord.thelion.website", "Matrix" = "https://matrix.thelion.website"}

anime_completed = [ {name = "91 Days", rating = "8/10", status = "x2"},
                    {name = "Akame ga Kill!", rating = "7/10", status = "x1"},
                    {name = "Aldnoah.Zero", rating = "?/10", status = "x1"},
                    {name = "Aldnoah.Zero (2015)", rating = "?/10", status = "x1"},
                    {name = "Angel Beats!", rating = "?/10", status = "x1"},
                    {name = "Another", rating = "?/10", status = "x1"},
                    {name = "Bakemonogatari", rating = "7/10", status = "x1"},
                    {name = "Blade Dance of Elementalers", rating = "9/10", status = "x1"},
                    {name = "Chaos;Head", rating = "?/10", status = "x1"},
                    {name = "Code Geass R1", rating = "10/10", status = "x4"},
                    {name = "Code Geass R2", rating = "10/10", status = "x4"},
                    {name = "Cowboy Bebop", rating = "6/10", status = "x1"},
                    {name = "Date a Live", rating = "?/10", status = "x1"},
                    {name = "Date a Live II", rating = "?/10", status = "x1"},
                    {name = "Deadman Wonderland", rating = "?/10", status = "x1"},
                    {name = "Death Note", rating = "10/10", status = "x4"},
                    {name = "Death Parade", rating = "?/10", status = "x1"},
                    {name = "Drifters", rating = "?/10", status = "x1"},
                    {name = "Durarara!!", rating = "8/10", status = "x1"},
                    {name = "Durarara!!x2 Ketsu", rating = "7/10", status = "x1"},
                    {name = "Durarara!!x2 Shou", rating = "8/10", status = "x1"},
                    {name = "Durarara!!x2 Ten", rating = "7/10", status = "x1"},
                    {name = "Erased", rating = "9/10", status = "x1"},
                    {name = "Golden Time", rating = "7/10", status = "x1"},
                    {name = "Elfen Lied", rating = "4/10", status = "x1"},
                    {name = "Guilty Crown", rating = "?/10", status = "x1"},
                    {name = "Halo Legends", rating = "?/10", status = "x1"},
                    {name = "High School DxD", rating = "?/10", status = "x1"},
                    {name = "High School DxD New", rating = "?/10", status = "x1"},
                    {name = "Hyouka", rating = "?/10", status = "x1"},
                    {name = "In Search of the Lost Future", rating = "?/10", status = "x1"},
                    {name = "K", rating = "?/10", status = "x1"},
                    {name = "K: Missing Kings", rating = "?/10", status = "x1"},
                    {name = "K: Return of Kings", rating = "?/10", status = "x1"},
                    {name = "Kill la Kill", rating = "?/10", status = "x1"},
                    {name = "Kiznaiver", rating = "6/10", status = "x1"},
                    {name = "Kokoro Connect", rating = "8/10", status = "x1"},
                    {name = "Konosuba", rating = "?/10", status = "x1"},
                    {name = "Legend of the Galactic Heroes", rating = "9/10", status = "x1"},
                    {name = "LOTGH: My Conquest is the Sea of Stars", rating = "9/10", status = "x1"},
                    {name = "LOTGH: Overture to a New War", rating = "9/10", status = "x1"},
                    {name = "Log Horizon", rating = "?/10", status = "x1"},
                    {name = "Mirai Nikki", rating = "?/10", status = "x1"},
                    {name = "Mirai Nikki Redial", rating = "?/10", status = "x1"},
                    {name = "Mob Psycho 100", rating = "8/10", status = "x2"},
                    {name = "Mob Psycho 100 II", rating = "9/10", status = "x1"},
                    {name = "Monster", rating = "9/10", status = "x1"},
                    {name = "Motto To Loveru", rating = "?/10", status = "x1"},
                    {name = "Naruto", rating = "7/10", status = "x1"},
                    {name = "Naruto Shippuden", rating = "8/10", status = "x1"},
                    {name = "Naruto the Movie : Ninja Clash in the Land of Snow", rating = "?/10", status = "x1"},
                    {name = "Nekomonogatari (Black): Tsubasa Family", rating = "8/10", status = "x1"},
                    {name = "Neon Genesis Evangelion", rating = "6/10", status = "x1"},
                    {name = "Nisemonogatari", rating = "7/10", status = "x1"},
                    {name = "No Game No Life", rating = "9/10", status = "x1"},
                    {name = "Occultic;Nine", rating = "?/10", status = "x1"},
                    {name = "One Punch Man", rating = "7/10", status = "x1"},
                    {name = "Prison School", rating = "7/10", status = "x2"},
                    {name = "Psycho Pass", rating = "?/10", status = "x1"},
                    {name = "Psycho Pass 2", rating = "?/10", status = "x1"},
                    {name = "School Days", rating = "?/10", status = "x1"},
                    {name = "Serial Experiments Lain", rating = "4/10", status = "x1"},
                    {name = "Shimoneta", rating = "7/10", status = "x1"},
                    {name = "Steins;Gate", rating = "10/10", status = "x3"},
                    {name = "Steins;Gate 0", rating = "10/10", status = "x2"},
                    {name = "Steins;Gate: Load Region of Deja Vu", rating = "8/10", status = "x1"},
                    {name = "Strike the Blood", rating = "?/10", status = "x1"},
                    {name = "Sword Art Online", rating = "7/10", status = "x2"},
                    {name = "Sword Art Online II", rating = "6/10", status = "x2"},
                    {name = "Terror in Resonance", rating = "?/10", status = "x2"},
                    {name = "The World God Only Knows", rating = "?/10", status = "x1"},
                    {name = "The World God Only Knows II", rating = "?/10", status = "x1"},
                    {name = "The World God Only Knows : Godesses", rating = "?/10", status = "x1"},
                    {name = "To Loveru", rating = "?/10", status = "x1"},
                    {name = "To Loveru : Darkness", rating = "?/10", status = "x1"},
                    {name = "Tokyo Ghoul", rating = "?/10", status = "x1"},
                    {name = "Tokyo Ghoul Root A", rating = "?/10", status = "x1"},
                    {name = "Toradora!", rating = "7/10", status = "x2"},
                    {name = "Unlimited Psychic Squad ", rating = "?/10", status = "x2"},
                    {name = "Vampire Knight", rating = "?/10", status = "x2"},
                    {name = "Vampire Knight Guilty", rating = "?/10", status = "x2"},
                    {name = "Welcome to the NHK", rating = "8/10", status = "x1"},
                    {name = "When Supernatural Battles Became Commonplace", rating = "?/10", status = "x1"},
                    {name = "Wolf Children", rating = "?/10", status = "x1"},
]
