baseURL = "https://thelion.website/"
languageCode = "en-us"
title = "The Lion"

paginate = "10"
enableEmoji = true

[author]
  name = "Lionir Deadman"
  url = "https://thelion.website/about/"
  avatar = "winter_elf_profile"

[taxonomies]
  tag = 'tags'

[permalinks]
  posts = '/posts/:filename/'
  ramblings = '/ramblings/:filename/'
  micro = '/micro/:filename/'

[outputFormats]
  [outputFormats.jsonfeed]
    mediaType = "application/json"
    baseName = "feed"
    isPlainText = true
    
  [outputFormats.atom]
    mediaType = "application/xml"
    baseName = "atom"
    isPlainText = true

  [outputFormats.logo]
    mediaType = "image/svg+xml"
    baseName = "logo"
    isPlainText = true

  [outputFormats.header]
    mediaType = "image/svg+xml"
    baseName = "header"
    isPlainText = true

  [outputFormats.stylesheet]
    mediaType = "text/css"
    baseName = "main"
    isPlainText = true

[outputs]
  home = ["html", "atom", "jsonfeed", "logo", "header", "stylesheet"]
  list = ["html"]
  term = ["html", "atom", "jsonfeed"]
  posts = ["html", "atom", "jsonfeed"]
  ramblings = ["html", "atom", "jsonfeed"]
  micro = ["html", "atom", "jsonfeed"]
  taxonomy = ["html"]
  single = ["html"]
  section = ["html"]
  page = ["html"]

[privacy.twitter]
  enableDNT = true
  simple = true

[privacy.youtube]
  privacyEnhanced = true

[params]
  # Orange ca1300 f05000
  # Purple 8410cc cc10b6
  # Blue   008dc9 00b8c9
  # Pink   d75090 f9426f
  # Autumn 731c12 b34410
  # Gold   e73602 dda30e
  primary_colour = "#008dc9"
  secondary_colour = "#00b8c9"
  icon = "/logo.svg"
  websub = "https://thelion.superfeedr.com"
  description = "Hi! I'm Lionir Deadman but just can just call me Lion for short. This is my website!"
  links = [ {url = "/feeds/", name = "Feeds"},
            {url = "/projects/", name = "Projects"},
            {url = "/tracking/", name = "Tracking"},
            {url = "/about/", name = "About"}
  ]
  [params.stylesheet]
    gap = 24
    content_gap = "20px"
    nav_width = "1024px"
    main_width = "640px"
    header_height = "300px"
    footer_height = "96px"
    radius = 20
    theme = "#fff"
    theme_bg = "#f0edee"
    entry = "#fff"
    primary = "#007ac6"
    secondary = "rgba(0, 0, 0, 0.56)"
    tertiary = "rgba(0, 0, 0, 0.16)"
    content = "rgba(0, 0, 0, 0.88)"
    code_bg = "#202024"
