baseURL = "https://thelion.website/"
languageCode = "en-us"
title = "The Lion"

paginate = "10"
disableKinds = ["taxonomy", "term"]
enableEmoji = true

[author]
  name = "Lionir Deadman"
  url = "https://thelion.website/about/"
  avatar = "mermelon_profile"

[outputFormats]
  [outputFormats.jsonfeed]
    mediaType = "application/json"
    baseName = "feed"
    isPlainText = true
    
  [outputFormats.atom]
    mediaType = "application/xml"
    baseName = "atom"
    isPlainText = true

  [outputFormats.logo]
    mediaType = "image/svg+xml"
    baseName = "logo"
    isPlainText = true

  [outputFormats.stylesheet]
    mediaType = "text/css"
    baseName = "main"
    isPlainText = true

[outputs]
  home = ["html","atom", "jsonfeed", "logo", "stylesheet"]
  list = ["html"]
  single = ["html"]
  section = ["html"]
  page = ["html"]

[privacy.twitter]
  enableDNT = true
  simple = true

[privacy.youtube]
  privacyEnhanced = true

[params]
  # Orange ca1300 f05000
  # Purple 8410cc cc10b6
  # Blue   008dc9 00b8c9
  # Pink   d75090 f9426f
  primary_colour = "#d75090"
  secondary_colour = "#f9426f"
  icon = "/logo.svg"
  websub = "https://thelion.superfeedr.com"
  description = "Hi! I'm Lionir Deadman but just can just call me Lion for short. This is my website!"
  links = [ {url = "/atom.xml", name = "Feed"},
            {url = "/projects/", name = "Projects"},
            {url = "/tracking/", name = "Tracking"},
            {url = "/about/", name = "About"}
  ]
