# The URL the site will be built for
base_url = "https://thelion.website"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "The Lion"

generate_feed = true
feed_filename = "atom.xml"
feed_url = "/atom.xml"

insert_anchor_links = "right"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
# Put all your custom variables here
links = [ {url = "/atom.xml", name = "Feed"},
	  {url = "/projects/", name = "Projects"},
	  {url = "/about/", name = "About"},
]

identities_social = {"Mastodon" = "https://mastodon.thelion.website"}
identities_editing = {"OpenStreetMap" = "https://openstreetmap.thelion.website", "Wikipedia" = "https://wikipedia.thelion.website"}
identities_discussion = {"Tildes" = "https://tildes.thelion.website", "Reddit" = "https://reddit.thelion.website", "GNOME Discourse" = "https://discourse-gnome.thelion.website"}
identities_coding = {"GitHub" = "https://github.thelion.website", "Codeberg" = "https://codeberg.thelion.website", "GitLab.com" = "https://gitlab.thelion.website", "GNOME GitLab" = "https://gitlab-gnome.thelion.website", "FreeDesktop GitLab" = "https://gitlab-freedesktop.thelion.website"}
identities_tracking = {"Anidb" = "https://anidb.thelion.website", "Listenbrainz" = "https://listen.thelion.website"}
identities_chatting = {"Discord (using a tool a friend made, pretty neat)" = "https://discord.thelion.website", "Matrix" = "https://matrix.thelion.website"}

anime_completed = [ {name = "91 Days", rating = "8/10", status = "Watched twice"},
                    {name = "Akame ga Kill!", rating = "7/10", status = "Watched once"},
                    {name = "Aldnoah.Zero", rating = "?/10", status = "Watched once"},
                    {name = "Aldnoah.Zero (2015)", rating = "?/10", status = "Watched once"},
                    {name = "Angel Beats!", rating = "?/10", status = "Watched once"},
                    {name = "Another", rating = "?/10", status = "Watched once"},
                    {name = "Bakemonogatari", rating = "7/10", status = "Watched once"},
                    {name = "Boku dake ga Inai Machi", rating = "9/10", status = "Watched once"},
                    {name = "Chaos;Head", rating = "?/10", status = "Watched once"},
                    {name = "Code Geass: Hangyaku no Lelouch", rating = "10/10", status = "Watched four times"},
                    {name = "Code Geass: Hangyaku no Lelouch R2", rating = "10/10", status = "Watched four times"},
                    {name = "Courtesy of Zettai Karen Children: The Unlimited - Hyoubu Kyousuke", rating = "?/10", status = "Watched once"},
                    {name = "Cowboy Bebop", rating = "6/10", status = "Watched once"},
                    {name = "Date a Live", rating = "?/10", status = "Watched once"},
                    {name = "Date a Live II", rating = "?/10", status = "Watched once"},
                    {name = "Deadman Wonderland", rating = "?/10", status = "Watched once"},
                    {name = "Death Note", rating = "10/10", status = "Watched four times"},
                    {name = "Death Parade", rating = "?/10", status = "Watched once"},
                    {name = "Drifters", rating = "?/10", status = "Watched once"},
                    {name = "Durarara!!", rating = "8/10", status = "Watched once"},
                    {name = "Durarara!!x2 Ketsu", rating = "7/10", status = "Watched once"},
                    {name = "Durarara!!x2 Shou", rating = "8/10", status = "Watched once"},
                    {name = "Durarara!!x2 Ten", rating = "7/10", status = "Watched once"},
                    {name = "Elfen Lied", rating = "4/10", status = "Watched once"},
                    {name = "Gekijouban K: Missing Kings", rating = "?/10", status = "Watched once"},
                    {name = "Gekijouban Naruto: Dai Katsugeki! Yuki Hime Ninpouchou Datte ba yo!", rating = "7/10", status = "Watched once"},
                    {name = "Ginga Eiyuu Densetsu", rating = "9/10", status = "Watched twice"},
                    {name = "Ginga Eiyuu Densetsu: Aratanaru Tatakai no Overture", rating = "9/10", status = "Watched once"},
                    {name = "Ginga Eiyuu Densetsu: Waga Yuku wa Hoshi no Taikai", rating = "9/10", status = "Watched once"},
                    {name = "Golden Time", rating = "7/10", status = "Watched once"},
                    {name = "Naruto", rating = "7.5/10", status = "Watched once"},
                    {name = "Steins;Gate", rating = "10/10", status = "Watched thrice"},
]
